
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module ShiftReg(clk, n_clr, s0, s1, sr_ser, sl_ser, abcd, q);
  input clk, n_clr, s0, s1, sr_ser, sl_ser;
  input [3:0] abcd;
  output [3:0] q;
  wire clk, n_clr, s0, s1, sr_ser, sl_ser;
  wire [3:0] abcd;
  wire [3:0] q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  QDFFRBX1 \temp_reg[0] (.RB (n_clr), .CK (clk), .D (n_13), .Q (q[0]));
  QDFFRBX1 \temp_reg[1] (.RB (n_clr), .CK (clk), .D (n_12), .Q (q[1]));
  QDFFRBX1 \temp_reg[2] (.RB (n_clr), .CK (clk), .D (n_14), .Q (q[2]));
  QDFFRBX1 \temp_reg[3] (.RB (n_clr), .CK (clk), .D (n_15), .Q (q[3]));
  ND2XLP g348(.I1 (n_11), .I2 (n_1), .O (n_15));
  ND2XLP g347(.I1 (n_2), .I2 (n_6), .O (n_14));
  ND2XLP g349(.I1 (n_5), .I2 (n_10), .O (n_13));
  ND2XLP g350(.I1 (n_0), .I2 (n_9), .O (n_12));
  AOI22XLP g357(.A1 (n_4), .A2 (q[3]), .B1 (n_3), .B2 (abcd[3]), .O
       (n_11));
  AOI22XLP g352(.A1 (n_7), .A2 (q[1]), .B1 (n_8), .B2 (sl_ser), .O
       (n_10));
  AOI22XLP g358(.A1 (n_8), .A2 (q[0]), .B1 (n_7), .B2 (q[2]), .O (n_9));
  AOI22XLP g353(.A1 (n_8), .A2 (q[1]), .B1 (n_7), .B2 (q[3]), .O (n_6));
  AOI22XLP g354(.A1 (n_4), .A2 (q[0]), .B1 (n_3), .B2 (abcd[0]), .O
       (n_5));
  AOI22XLP g355(.A1 (n_4), .A2 (q[2]), .B1 (n_3), .B2 (abcd[2]), .O
       (n_2));
  AOI22XLP g356(.A1 (n_8), .A2 (q[2]), .B1 (n_7), .B2 (sr_ser), .O
       (n_1));
  AOI22XLP g351(.A1 (n_4), .A2 (q[1]), .B1 (n_3), .B2 (abcd[1]), .O
       (n_0));
  AN2B1XLP g359(.I1 (s1), .B1 (s0), .O (n_8));
  AN2B1XLP g360(.I1 (s0), .B1 (s1), .O (n_7));
  NR2XLP g361(.I1 (s0), .I2 (s1), .O (n_4));
  AN2XLP g362(.I1 (s1), .I2 (s0), .O (n_3));
endmodule

