/*
###############################################################
#  Generated by:      Cadence Encounter 13.13-s017_1
#  OS:                Linux x86_64(Host ID drain9)
#  Generated on:      Thu Nov  3 20:46:23 2016
#  Design:            ShiftReg
#  Command:           saveNetlist ShiftReg.v
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1
module ShiftReg (
	clk, 
	n_clr, 
	s0, 
	s1, 
	sr_ser, 
	sl_ser, 
	abcd, 
	q);
   input clk;
   input n_clr;
   input s0;
   input s1;
   input sr_ser;
   input sl_ser;
   input [3:0] abcd;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;

   QDFFRBX1 \temp_reg[0]  (.RB(n_clr),
	.Q(q[0]),
	.D(n_13),
	.CK(clk));
   QDFFRBX1 \temp_reg[1]  (.RB(n_clr),
	.Q(q[1]),
	.D(n_12),
	.CK(clk));
   QDFFRBX1 \temp_reg[2]  (.RB(n_clr),
	.Q(q[2]),
	.D(n_14),
	.CK(clk));
   QDFFRBX1 \temp_reg[3]  (.RB(n_clr),
	.Q(q[3]),
	.D(n_15),
	.CK(clk));
   ND2XLP g348 (.O(n_15),
	.I2(n_1),
	.I1(n_11));
   ND2XLP g347 (.O(n_14),
	.I2(n_6),
	.I1(n_2));
   ND2XLP g349 (.O(n_13),
	.I2(n_10),
	.I1(n_5));
   ND2XLP g350 (.O(n_12),
	.I2(n_9),
	.I1(n_0));
   AOI22XLP g357 (.O(n_11),
	.B2(abcd[3]),
	.B1(n_3),
	.A2(q[3]),
	.A1(n_4));
   AOI22XLP g352 (.O(n_10),
	.B2(sl_ser),
	.B1(n_8),
	.A2(q[1]),
	.A1(n_7));
   AOI22XLP g358 (.O(n_9),
	.B2(q[2]),
	.B1(n_7),
	.A2(q[0]),
	.A1(n_8));
   AOI22XLP g353 (.O(n_6),
	.B2(q[3]),
	.B1(n_7),
	.A2(q[1]),
	.A1(n_8));
   AOI22XLP g354 (.O(n_5),
	.B2(abcd[0]),
	.B1(n_3),
	.A2(q[0]),
	.A1(n_4));
   AOI22XLP g355 (.O(n_2),
	.B2(abcd[2]),
	.B1(n_3),
	.A2(q[2]),
	.A1(n_4));
   AOI22XLP g356 (.O(n_1),
	.B2(sr_ser),
	.B1(n_7),
	.A2(q[2]),
	.A1(n_8));
   AOI22XLP g351 (.O(n_0),
	.B2(abcd[1]),
	.B1(n_3),
	.A2(q[1]),
	.A1(n_4));
   AN2B1XLP g359 (.O(n_8),
	.I1(s1),
	.B1(s0));
   AN2B1XLP g360 (.O(n_7),
	.I1(s0),
	.B1(s1));
   NR2XLP g361 (.O(n_4),
	.I2(s1),
	.I1(s0));
   AN2XLP g362 (.O(n_3),
	.I2(s0),
	.I1(s1));
endmodule

