/*
###############################################################
#  Generated by:      Cadence Encounter 13.13-s017_1
#  OS:                Linux x86_64(Host ID drain12)
#  Generated on:      Tue Apr 12 14:16:35 2016
#  Design:            counter
#  Command:           saveNetlist counter.v
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1
module counter (
	clk, 
	rst, 
	load, 
	up, 
	cin, 
	cout);
   input clk;
   input rst;
   input load;
   input up;
   input [7:0] cin;
   output [7:0] cout;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;

   QDFFRBX1 \cout_x_reg[7]  (.RB(rst),
	.Q(cout[7]),
	.D(n_45),
	.CK(clk));
   OAI112XLP g898 (.O(n_45),
	.C2(cout[7]),
	.C1(n_37),
	.B1(n_2),
	.A1(n_42));
   OR2B1XLP g902 (.O(n_44),
	.I1(n_35),
	.B1(n_40));
   AO222XLP g900 (.O(n_43),
	.C2(cin[6]),
	.C1(load),
	.B2(cout[6]),
	.B1(n_41),
	.A2(n_36),
	.A1(n_34));
   OAI12XLP g903 (.O(n_42),
	.B2(n_8),
	.B1(n_41),
	.A1(cout[7]));
   AOI222XLP g905 (.O(n_40),
	.C2(cin[5]),
	.C1(load),
	.B2(cout[5]),
	.B1(n_39),
	.A2(n_13),
	.A1(n_26));
   OR2B1XLP g909 (.O(n_41),
	.I1(n_39),
	.B1(n_14));
   OAI112XLP g904 (.O(n_38),
	.C2(n_29),
	.C1(n_31),
	.B1(n_27),
	.A1(n_23));
   MXL2XLP g906 (.S(n_36),
	.OB(n_37),
	.B(n_35),
	.A(n_33));
   OR2XLP g908 (.O(n_34),
	.I2(n_33),
	.I1(n_35));
   OAI122XLP g913 (.O(n_32),
	.C2(n_17),
	.C1(n_28),
	.B2(n_30),
	.B1(n_20),
	.A1(n_1));
   QDFFRBX1 \cout_x_reg[1]  (.RB(rst),
	.Q(cout[1]),
	.D(n_24),
	.CK(clk));
   OAI122XLP g912 (.O(n_39),
	.C2(n_28),
	.C1(cout[4]),
	.B2(n_29),
	.B1(n_30),
	.A1(n_31));
   NR2XLP g910 (.O(n_35),
	.I2(n_27),
	.I1(cout[5]));
   AN2XLP g911 (.O(n_33),
	.I2(cout[5]),
	.I1(n_26));
   AO222XLP g919 (.O(n_25),
	.C2(n_22),
	.C1(n_7),
	.B2(n_18),
	.B1(n_9),
	.A2(cin[2]),
	.A1(load));
   OAI12XLP g925 (.O(n_24),
	.B2(n_28),
	.B1(n_15),
	.A1(n_16));
   AOI23XLP g914 (.O(n_23),
	.B3(n_29),
	.B2(n_22),
	.B1(n_21),
	.A2(cin[4]),
	.A1(load));
   OA22XLP g917 (.O(n_31),
	.B2(n_28),
	.B1(n_21),
	.A2(n_19),
	.A1(n_30));
   AOI12XLP g920 (.O(n_20),
	.B2(cout[3]),
	.B1(n_10),
	.A1(n_19));
   ND3XLP g915 (.O(n_27),
	.I3(n_29),
	.I2(n_18),
	.I1(n_19));
   AN3XLP g916 (.O(n_26),
	.I3(cout[4]),
	.I2(n_22),
	.I1(n_21));
   MXL2XLP g921 (.S(n_11),
	.OB(n_17),
	.B(cout[3]),
	.A(n_12));
   AOI22XLP g927 (.O(n_16),
	.B2(cin[1]),
	.B1(load),
	.A2(n_18),
	.A1(n_15));
   MXL2XLP g932 (.S(n_13),
	.OB(n_14),
	.B(n_22),
	.A(n_18));
   NR2XLP g923 (.O(n_21),
	.I2(n_11),
	.I1(n_12));
   NR2XLP g924 (.O(n_19),
	.I2(n_10),
	.I1(cout[3]));
   OAI12XLP g926 (.O(n_9),
	.B2(n_6),
	.B1(n_5),
	.A1(n_10));
   MXL2XLP g933 (.S(n_36),
	.OB(n_8),
	.B(n_28),
	.A(n_30));
   QDFZRBX1 \cout_x_reg[0]  (.TD(cin[0]),
	.SEL(load),
	.RB(rst),
	.Q(cout[0]),
	.D(n_3),
	.CK(clk));
   MXL2XLP g928 (.S(n_4),
	.OB(n_7),
	.B(n_6),
	.A(cout[2]));
   ND2XLP g929 (.O(n_10),
	.I2(n_6),
	.I1(n_5));
   OR2XLP g930 (.O(n_11),
	.I2(n_4),
	.I1(n_6));
   MXL2XLP g934 (.S(cout[1]),
	.OB(n_15),
	.B(n_3),
	.A(cout[0]));
   INVCKXLP g940 (.O(n_22),
	.I(n_28));
   ND2XLP g941 (.O(n_28),
	.I2(up),
	.I1(n_0));
   INVCKXLP g936 (.O(n_30),
	.I(n_18));
   ND2XLP g939 (.O(n_2),
	.I2(cin[7]),
	.I1(load));
   NR2XLP g942 (.O(n_5),
	.I2(cout[0]),
	.I1(cout[1]));
   NR2XLP g937 (.O(n_18),
	.I2(load),
	.I1(up));
   ND2XLP g938 (.O(n_1),
	.I2(cin[3]),
	.I1(load));
   ND2XLP g935 (.O(n_4),
	.I2(cout[1]),
	.I1(cout[0]));
   INVCKXLP g946 (.O(n_3),
	.I(cout[0]));
   INVCKXLP g948 (.O(n_0),
	.I(load));
   DFFRBX1 \cout_x_reg[4]  (.RB(rst),
	.QB(n_29),
	.Q(cout[4]),
	.D(n_38),
	.CK(clk));
   DFFRBX1 \cout_x_reg[3]  (.RB(rst),
	.QB(n_12),
	.Q(cout[3]),
	.D(n_32),
	.CK(clk));
   DFFRBX1 \cout_x_reg[6]  (.RB(rst),
	.QB(n_36),
	.Q(cout[6]),
	.D(n_43),
	.CK(clk));
   DFFRBX1 \cout_x_reg[5]  (.RB(rst),
	.QB(n_13),
	.Q(cout[5]),
	.D(n_44),
	.CK(clk));
   DFFRBX1 \cout_x_reg[2]  (.RB(rst),
	.QB(n_6),
	.Q(cout[2]),
	.D(n_25),
	.CK(clk));
endmodule

