
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module counter(clk, rst, load, up, cin, cout);
  input clk, rst, load, up;
  input [7:0] cin;
  output [7:0] cout;
  wire clk, rst, load, up;
  wire [7:0] cin;
  wire [7:0] cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45;
  QDFFRBX1 \cout_x_reg[7] (.RB (rst), .CK (clk), .D (n_45), .Q
       (cout[7]));
  OAI112XLP g898(.A1 (n_42), .B1 (n_2), .C1 (n_37), .C2 (cout[7]), .O
       (n_45));
  OR2B1XLP g902(.I1 (n_35), .B1 (n_40), .O (n_44));
  AO222XLP g900(.A1 (n_34), .A2 (n_36), .B1 (n_41), .B2 (cout[6]), .C1
       (load), .C2 (cin[6]), .O (n_43));
  OAI12XLP g903(.A1 (cout[7]), .B1 (n_41), .B2 (n_8), .O (n_42));
  AOI222XLP g905(.A1 (n_26), .A2 (n_13), .B1 (n_39), .B2 (cout[5]), .C1
       (load), .C2 (cin[5]), .O (n_40));
  OR2B1XLP g909(.I1 (n_39), .B1 (n_14), .O (n_41));
  OAI112XLP g904(.A1 (n_23), .B1 (n_27), .C1 (n_31), .C2 (n_29), .O
       (n_38));
  MXL2XLP g906(.S (n_36), .A (n_33), .B (n_35), .OB (n_37));
  OR2XLP g908(.I1 (n_35), .I2 (n_33), .O (n_34));
  OAI122XLP g913(.A1 (n_1), .B1 (n_20), .B2 (n_30), .C1 (n_28), .C2
       (n_17), .O (n_32));
  QDFFRBX1 \cout_x_reg[1] (.RB (rst), .CK (clk), .D (n_24), .Q
       (cout[1]));
  OAI122XLP g912(.A1 (n_31), .B1 (n_30), .B2 (n_29), .C1 (cout[4]), .C2
       (n_28), .O (n_39));
  NR2XLP g910(.I1 (cout[5]), .I2 (n_27), .O (n_35));
  AN2XLP g911(.I1 (n_26), .I2 (cout[5]), .O (n_33));
  AO222XLP g919(.A1 (load), .A2 (cin[2]), .B1 (n_9), .B2 (n_18), .C1
       (n_7), .C2 (n_22), .O (n_25));
  OAI12XLP g925(.A1 (n_16), .B1 (n_15), .B2 (n_28), .O (n_24));
  AOI23XLP g914(.A1 (load), .A2 (cin[4]), .B1 (n_21), .B2 (n_22), .B3
       (n_29), .O (n_23));
  OA22XLP g917(.A1 (n_30), .A2 (n_19), .B1 (n_21), .B2 (n_28), .O
       (n_31));
  AOI12XLP g920(.A1 (n_19), .B1 (n_10), .B2 (cout[3]), .O (n_20));
  ND3XLP g915(.I1 (n_19), .I2 (n_18), .I3 (n_29), .O (n_27));
  AN3XLP g916(.I1 (n_21), .I2 (n_22), .I3 (cout[4]), .O (n_26));
  MXL2XLP g921(.S (n_11), .A (n_12), .B (cout[3]), .OB (n_17));
  AOI22XLP g927(.A1 (n_15), .A2 (n_18), .B1 (load), .B2 (cin[1]), .O
       (n_16));
  MXL2XLP g932(.S (n_13), .A (n_18), .B (n_22), .OB (n_14));
  NR2XLP g923(.I1 (n_12), .I2 (n_11), .O (n_21));
  NR2XLP g924(.I1 (cout[3]), .I2 (n_10), .O (n_19));
  OAI12XLP g926(.A1 (n_10), .B1 (n_5), .B2 (n_6), .O (n_9));
  MXL2XLP g933(.S (n_36), .A (n_30), .B (n_28), .OB (n_8));
  QDFZRBX1 \cout_x_reg[0] (.RB (rst), .CK (clk), .D (n_3), .TD
       (cin[0]), .SEL (load), .Q (cout[0]));
  MXL2XLP g928(.S (n_4), .A (cout[2]), .B (n_6), .OB (n_7));
  ND2XLP g929(.I1 (n_5), .I2 (n_6), .O (n_10));
  OR2XLP g930(.I1 (n_6), .I2 (n_4), .O (n_11));
  MXL2XLP g934(.S (cout[1]), .A (cout[0]), .B (n_3), .OB (n_15));
  INVCKXLP g940(.I (n_28), .O (n_22));
  ND2XLP g941(.I1 (n_0), .I2 (up), .O (n_28));
  INVCKXLP g936(.I (n_18), .O (n_30));
  ND2XLP g939(.I1 (load), .I2 (cin[7]), .O (n_2));
  NR2XLP g942(.I1 (cout[1]), .I2 (cout[0]), .O (n_5));
  NR2XLP g937(.I1 (up), .I2 (load), .O (n_18));
  ND2XLP g938(.I1 (load), .I2 (cin[3]), .O (n_1));
  ND2XLP g935(.I1 (cout[0]), .I2 (cout[1]), .O (n_4));
  INVCKXLP g946(.I (cout[0]), .O (n_3));
  INVCKXLP g948(.I (load), .O (n_0));
  DFFRBX1 \cout_x_reg[4] (.RB (rst), .CK (clk), .D (n_38), .Q
       (cout[4]), .QB (n_29));
  DFFRBX1 \cout_x_reg[3] (.RB (rst), .CK (clk), .D (n_32), .Q
       (cout[3]), .QB (n_12));
  DFFRBX1 \cout_x_reg[6] (.RB (rst), .CK (clk), .D (n_43), .Q
       (cout[6]), .QB (n_36));
  DFFRBX1 \cout_x_reg[5] (.RB (rst), .CK (clk), .D (n_44), .Q
       (cout[5]), .QB (n_13));
  DFFRBX1 \cout_x_reg[2] (.RB (rst), .CK (clk), .D (n_25), .Q
       (cout[2]), .QB (n_6));
endmodule

